### ISSUE TITLE
Desenvolver a política de reconhecimento SUMO

### ISSUE THREAD

**Issue by zilmarr** [mozillabrasil/metas#10]
## Meta:

Desenvolver o Sistema de Reconhecimento para contribuidores do SUMO Brasil
## Roles:
- (R)esponsável: Zilmar de Souza Junior
- (A)ccountable (responsable em última instância):
- (S)uporte:
- (C)onsultado:
- (I)nformado: 
## Tarefas:
- [x] [Chamada no discourse](https://discourse.mozilla-community.org/t/politica-de-reconhecimento-projeto/10007)
- [x] [Brainstorming inicial](https://public.etherpad-mozilla.org/p/sumo-sistema-reconhecimento-brainstorm)
- [ ] Consolidação de ideias

**Comment by cpswsg** [comment]
@ziww posso ajudar no desenvolvimento desse sistema.

**Comment by zilmarr** [comment]
PAD de brainstorming: https://public.etherpad-mozilla.org/p/sumo-sistema-reconhecimento-brainstorm

**Comment by halcance** [comment]
@ziww  Olá, posso ajudar no que precisar, desde desenvolvimento do sistema até revisões

**Comment by Jedarc** [comment]
Opa, estou dentro caso ainda precisem!
