### ISSUE TITLE
Tradução do Community Playbook

### ISSUE THREAD

**Issue by cpswsg** [mozillabrasil/metas#11]
## Meta:

Tradução do [Community Playbook](https://wiki.mozilla.org/Participation/Community_Playbook) com destaque para a área de [onboarding e engajamento](https://wiki.mozilla.org/Participation/Community_Playbook#Onboarding_and_engagement).
## Links / tarefas relacionadas:
#7
## Roles:
- (R)esponsável: @jaimemaretoli
- (A)ccountable (responsable em última instância): @mozillabrasil/onboarding
- (S)uporte: @mozillabrasil
- (C)onsultado: @mozillabrasil
- (I)nformado: @mozillabrasil
## Tarefas:
- [X] Criar uma pad para facilitar a localização (https://public.etherpad-mozilla.org/p/community-playbook-br)
- [x] Revisar o conteúdo localizado
- [x] Criar uma página na Wiki da comunidade

**Comment by maykonchagas** [comment]
A quem possa interessar, já falei com @cynthiapereira através do IRC e vou colaborar na tradução do Playbook. Já comecei a traduzir. Peguei o [código original](https://wiki.mozilla.org/index.php?title=Participation/Community_Playbook&action=edit) da wiki [Community Playbook](https://wiki.mozilla.org/Participation/Community_Playbook). O trabalho em andamento está no [meu repositório](https://github.com/mchagas/Mozilla.git) do Github.

Atenciosamente

**Comment by maykonchagas** [comment]
@cynthiapereira já traduzi o playbook, disponível no [meu repositório](https://github.com/mchagas/Mozilla.git). Acho que poderia adicionar uma tarefa, antes da revisão, tradução do playbook, por que disponibilizar para localização e traduzir, são duas tarefas diferentes .p~ 
No mais, agora falta uma revisão maneira.

**Comment by halcance** [comment]
Olá @mchagas  revisei seu conteúdo, obrigado pela colaboração.

**Comment by cpswsg** [comment]
@mchagas e @alipseight  Muito obrigada! 

@alipseight onde podemos verificar o conteúdo revisado?

**Comment by halcance** [comment]
@cynthiapereira seria bom criar um repositório no github para colocar documentos lá que precisam ser revisados/criados/traduzidos lá na Wiki ou em outros locais.

**Comment by cpswsg** [comment]
@alipseight podemos usar esse repo @mozillabrasil/onboarding para colocar os arquivos.

**Comment by halcance** [comment]
Irei fazer isso agora mesmo @cynthiapereira

**Comment by halcance** [comment]
@mchagas poderia aceitar o pull request da @cynthiapereira para a revisão feita pela mesma e depois, iremos postar no nosso repositório onboaring @mozillabrasil/onboarding

**Comment by maykonchagas** [comment]
@cynthiapereira @alipseight pull request aceito! valeu pessoal, gostaria de continuar colaborando, se tiver mais coisas para poder traduzir/revisar, me dêem um toque que eu começo tão logo seja possível! abraços

**Comment by halcance** [comment]
Obrigado @mchagas, sempre temos coisinhas para traduzir! principalmente no nosso [fórum L10n](https://support.mozilla.org/pt-BR/localization). Toda contribuição é bem vinda, fique atento nos nossos repositórios.

**Comment by barrosgg** [comment]
Vou adicionar este na wiki.

**Comment by torto** [comment]
Já não está na wiki? https://wiki.mozilla.org/Brasil/Onboarding/Manual_da_Comunidade

**Comment by barrosgg** [comment]
Hum, me pediram pra colocar, são tantos locais de comunicação, acabei me perdendo então, aqui não estava o link e nem foi mencionado adicionaram na wiki.

@torto, obrigado.
