### ISSUE TITLE
Definição dos papéis e Equipes Operacionais do time de Onbording

### ISSUE THREAD

**Issue by torto** [mozillabrasil/metas#12]
## Meta:

Definir papéis para cada pessoa e assim definir equipes operacionais do time onbording, baseando no playbook #11 
## Links / tarefas relacionadas:
#7
## Roles:
- (R)esponsável: @torto 
- (A)ccountable (responsable em última instância): @mozillabrasil/onboarding.
- (S)uporte: @mozillabrasil
- (C)onsultado: @mozillabrasil
- (I)nformado: @mozillabrasil
## Tarefas:
- [x] Criar um tópico no discurse para pessoas falarem um pouco sobre elas (@torto)
- [ ] Definir em reunião quais papéis cada pessoa que respondeu tem. (@mozillabrasil/onboarding)
- [ ] Criar um pad para catalogar os papéis encontrados nas respostas das pessoas (@torto)
- [ ] Definir em reunião quais equipes operacionais o time terá (@mozillabrasil/onboarding)
- [ ] Criar uma documentação (wiki, pad) que facilite as pessoas encontrarem quem são as pessoas e coordenadores dessas equipes (@mozillabrasil/onboarding)

**Comment by torto** [comment]
https://discourse.mozilla-community.org/t/definicao-de-papeis-do-time-de-onboarding/10592

**Comment by halcance** [comment]
Criado um pad para adicionar os membros e mentores até  a reunião para definir os coordenadores

https://public.etherpad-mozilla.org/p/Mozilla_Brasil__Onboarding

**Comment by torto** [comment]
@alipseight calma meu amigo, uma coisa de cada vez :heart: precisamos ainda definir os papéis.

**Comment by halcance** [comment]
Sim, mas enquanto não fazemos isso já listamos o pad com descrições para facilitar o engajamento :heart:

**Comment by Jedarc** [comment]
Temos que tentar dar mais uma divulgada pra galera poder participar...

**Comment by halcance** [comment]
@jedarc parece que o repositório está abandonado

**Comment by Jedarc** [comment]
@alipseight infelizmente é o que parece mesmo... :(

**Comment by cpswsg** [comment]
@alipseight e @Jedarc por favor, entrem em contato com o @jaimemaretoli que é o responsável por essa task.

**Comment by jaimemaretoli** [comment]
@alipseight @cynthiapereira @Jedarc: Pessoal, documentamos tudo na nossa Wiki, deem uma olhada: https://wiki.mozilla.org/Brasil/Onboarding/

Restam algumas pendencias dos times funcionais, para organizarem seus guias de início — nos quais, o status também está na [Wiki](https://wiki.mozilla.org/Brasil/Onboarding/).

Acredito que essa task pode ser encerrada, confere @barrosgeraldo?

**Comment by barrosgeraldo** [comment]
@jaimemaretoli, a tarefa dessa issue em si não foi definida que é a Definição dos papéis e Equipes Operacionais do time de Onbording.
