### ISSUE TITLE
Começamos a documentar atividades através de meios de comunicação comunitários

### ISSUE THREAD

**Issue by nukeador** [mozillabrasil/metas#2]
_Problema: A falta de transparência na tomada de decisões_
## Meta:

Começamos a documentar atividades através de meios de comunicação comunitários
## Roles:
- (R)esponsável:
- (A)ccountable (responsable em última instância):
- (S)uporte:
- (C)onsultado:
- (I)nformado: 
## Tarefas:
- [ ] 90% das actividades em junho foram relatados nos canais (responsável)

**Comment by halcance** [comment]
Creio que isso não será mais necessário já que o time de onboarding já está fazendo isso.

**Comment by cpswsg** [comment]
O [canal da comunidade no Discourse](https://discourse.mozilla-community.org/c/mozilla-brasil) é a fonte para toda a comunicação dos times funcionais e membros da comunidade.
