### ISSUE TITLE
Identificar colaboradores em cada região

### ISSUE THREAD

**Issue by nukeador** [mozillabrasil/metas#4]
_Problema: A tomada de decisão é focado no sul e sudoeste_
## Meta:

[Descrição de uma linha] 
## Links / tarefas relacionadas:

[Outras issues] #
## Roles:
- (R)esponsável: Zilmar de Souza Junior
- (A)ccountable (responsable em última instância):
- (S)uporte:
- (C)onsultado:
- (I)nformado: 
## Tarefas:
- [x] Criar um formulário para fazer o censo (Zilmar de Souza Junior)
- [x] Documentar este censo (responsável)

**Comment by zilmarr** [comment]
Formulário criado: https://goo.gl/forms/Dl4mrHBcQNXHgses1

**Comment by zilmarr** [comment]
Resultado: https://discourse.mozilla-community.org/t/onde-voce-mora-identificando-onde-estao-nossos-membros/9947/1
