### ISSUE TITLE
Documentação de Times/Projetos

### ISSUE THREAD

**Issue by marinalimeira** [mozillabrasil/metas#5]
Problema: Falta de informações sobre os projetos que a Mozilla Brasil desenvolve;
## Meta:

Reunir informações sobre os projetos que a Mozilla Brasil desenvolve.
## Links / tarefas relacionadas:

[Outras issues] #
## Roles:
- (R)esponsável: @marinalimeira @torto
- (A)ccountable (responsable em última instância): @torto
- (S)uporte: @jaimemaretoli @dutrafox
- (C)onsultado: Toda comunidade
- (I)nformado: Toda a comunidade
## Tarefas:
- [x] Abrir discussão no Discourse; {R: @marinalimeira}
- [x] Compartilhar o link do Discourse na lista de e-mails; {R: @marinalimeira}
- [ ] Catalogar no wiki da Mozilla. {R: @torto}

**Comment by torto** [comment]
Link do discourse: https://discourse.mozilla-community.org/t/projetos-e-times-ativos-na-comunidade/8971

**Comment by torto** [comment]
Classificação temporária: https://public.etherpad-mozilla.org/p/projetos-mozilla-br

**Comment by jaimemaretoli** [comment]
Precisam de alguma ajuda? @torto vamos aguardar mais pra catalogar na Wiki? Até quando? Contem comigo.

**Comment by torto** [comment]
@jaimemaretoli estou em viagem, pretendo antes de catalogar na wiki, escrever um pequeno resumo sobre cada projeto e ai sim inserir lá.
Vejo isso amanhã quando voltar para casa 12/06

**Comment by felipez3r0** [comment]
Pessoal, algum retorno sobre esse processo? Precisando de alguma ajuda avisem :smile:

**Comment by jaimemaretoli** [comment]
@felipez3r0 Acho que falta apenas documentar na Wiki mesmo Felipe, conforme o Pad e o tópico no Discourse. Como o @torto não pode no momento, se quiser dar uma puxada nisso, conte com a minha ajuda. Beleza @felipez3r0?

**Comment by felipez3r0** [comment]
@jaimemaretoli Vamos tentar conversar no início da próxima semana para realizar isso? (Depois do dia 01/08)

**Comment by jaimemaretoli** [comment]
@felipez3r0 [Abri um tópico no Discourse](https://discourse.mozilla-community.org/t/inicio-da-definicao-processo-de-onboarding-da-comunidade-mozilla-brasil/9937/6), deixarei um tempo o tópico por lá pra ver se o pessoal vai discutir, dar seus "pitacos" por lá. Depois disso planejo abrir um Doodle e Pad (planejo isso pro dia 08/08) para marcar nossa reunião e colocar todas as questões em discussão. O que acha disso? Se tem alguma consideração e etc, não deixa de colocar lá no tópico. ;-)

**Comment by jaimemaretoli** [comment]
Pad e Doodle abertos pessoal: https://discourse.mozilla-community.org/t/inicio-da-definicao-processo-de-onboarding-da-comunidade-mozilla-brasil/9937/12?u=jaimemaretoli

**Comment by halcance** [comment]
Andamento da meta ?

**Comment by jaimemaretoli** [comment]
@alipseight ainda falta documentar na Wiki, até onde eu sei, somente isso.

**Comment by cpswsg** [comment]
@jaimemaretoli essa tarefa foi concluída? Podemos encerrar essa issue?

**Comment by jaimemaretoli** [comment]
@cynthiapereira @alipseight existem pendências com alguns times funcionais — Guia de Início de cada time — conforme Wiki: https://wiki.mozilla.org/Brasil/Onboarding/
