### ISSUE TITLE
Criar o estatuto do conselho de resolução de conflitos

### ISSUE THREAD

**Issue by soapdog** [mozillabrasil/metas#6]
## Meta:

Criar o estatuto do conselho de resolução de conflitos
## Links / tarefas relacionadas:

 #1
## Roles:
- (R)esponsável: @dricupello @felipez3r0
- (A)ccountable (responsable em última instância): @dricupello
- (S)uporte: @luiguild @soapdog @rodrigowaters @dbarjs @edivaniadias
- (C)onsultado: Mozilla Brasil
- (I)nformado: Mozilla Brasil
## Tarefas:
- [x] Pesquisar outros estatutos similares em organizações diversas.
- [x] Elaboração do estatuto
- [x] Aguardar e analisar as respostas da comunidade (formulário de interesse de participação no conselho)
- [x] Estabelecer a criação de normas no estatuto para eleição (nomeação) de novos membros, e, incluse o ciclo de rotatividade
- [ ] Criar diagramas/fluxogramas com explicações sobre o conselho

**Comment by dbarjs** [comment]
Não são estatutos, mas possuem coisas (referências) que poderão colaborar com a criação do estatuto e SOPs:
https://www.trt3.jus.br/download/artigos/pdf/20_formas_resolucao_conflitos.pdf
http://members.lionsclubs.org/PO/leos/leadership-opportunities/club-leadership/addressing-resolving-conflict.php

**Comment by felipez3r0** [comment]
Esse link tem um modelo de estatuto que pode servir como base para a formulação do estatuto do conselho da comunidade:

http://www.ibgc.org.br/userfiles/files/Caderno%205.pdf

**Comment by dricupello** [comment]
@edivaniadias pode subir o documento que a gente começou pra um google drive e compartilhar com a gente? aí se quisermos colocar alguma coisa nele ou até reler a gente pode.

**Comment by dbarjs** [comment]
https://docs.google.com/document/d/1IFe92tcscESItZ06tEnsPkX62xHp9ooyZ0rvTD1Imf0/edit?usp=sharing

Valeu @edivaniadias

**Comment by dbarjs** [comment]
O estatuto[1] já está avançando e vários pontos ainda estão sendo discutidos. O documento foi atualizado com base na reunião (hangout) que fizemos hoje, na qual estavam presentes @edivaniadias, @barrosgeraldo, @cynthiapereira e eu. Um etherpad [2] foi criado para adicionar todos os pontos discutidos.

Links:
[1] https://docs.google.com/document/d/1IFe92tcscESItZ06tEnsPkX62xHp9ooyZ0rvTD1Imf0/edit?usp=sharing
[2] https://public.etherpad-mozilla.org/p/conselho-resolucao-conflitos2

**Comment by dbarjs** [comment]
Um post (discourse) com uma pesquisa parar analisarmos a quantidade de pessoas que tem interesse de entrar para o conselho está disponível no link:

https://discourse.mozilla-community.org/t/interesse-em-fazer-parte-do-conselho-de-resolucao-de-conflitos/9335/13

**Comment by ghost** [comment]
Muito obrigada pelo update Eduardo!

**Comment by felipez3r0** [comment]
A versão 1.0 do estatuto está praticamente finalizada:
https://docs.google.com/document/d/1IFe92tcscESItZ06tEnsPkX62xHp9ooyZ0rvTD1Imf0

A data final para manifesto de interesse de participar do Conselho de Resolução de Conflitos ficou definida para dia 31/07. A reunião posterior será para verificar o número de interessados e iniciar o processo de formação do primeiro grupo de conselheiros.

Link do Pad com os detalhes das últimas reuniões:
https://public.etherpad-mozilla.org/p/conselho-resolucao-conflitos

**Comment by halcance** [comment]
O documento foi criado e pode ser acessado aqui: https://docs.google.com/document/d/1IFe92tcscESItZ06tEnsPkX62xHp9ooyZ0rvTD1Imf0

Link no discourse:

https://discourse.mozilla-community.org/c/mozilla-brasil/resolucao-de-conflitos
