### ISSUE TITLE
Definição do processo de onboarding

### ISSUE THREAD

**Issue by marinalimeira** [mozillabrasil/metas#7]
_Problema: Atualmente não existe um processo que guie novos membros da comunidade, o que dificulta a captação e retenção desses novos voluntários_
## Meta:

Definição de uma abordagem ideal para onboarding.
## Links / tarefas relacionadas:
#5
## Roles:
- (R)esponsável:
- (A)ccountable (responsable em última instância):
- (S)uporte:
- (C)onsultado: Toda a comunidade
- (I)nformado: Toda a comunidade
## Tarefas:
- [ ] Iniciar discussão no Discourse

**Comment by torto** [comment]
Precisamos definir o RASCI para esse meta. Quando podemos conversar?

**Comment by torto** [comment]
Será que vamos conseguir definir isso até final do mês? Não ficou acertado de fazermos a #5 esse mês?

**Comment by jaimemaretoli** [comment]
@torto, @marinalimeira e @dutrafox. Podemos definir o RASCI sim, bora conversar, assim já matamos todas as pendências: http://doodle.com/poll/bsdtceixfgrd8rth

**Comment by jaimemaretoli** [comment]
Discussão aberta pessoal: https://discourse.mozilla-community.org/t/inicio-da-definicao-processo-de-onboarding-da-comunidade-mozilla-brasil/9937

**Comment by jaimemaretoli** [comment]
Pad e Doodle abertos para a primeira reunião: https://discourse.mozilla-community.org/t/inicio-da-definicao-processo-de-onboarding-da-comunidade-mozilla-brasil/9937/12?u=jaimemaretoli

**Comment by barrosgg** [comment]
@jaimemaretoli, encerre o Doodle, mais informações no tópico do Discourse.

**Comment by jaimemaretoli** [comment]
@barrosgeraldo Doodle Encerrado! Muito obrigado.

**Comment by cpswsg** [comment]
@jaimemaretoli pode passar um status sobre isso?

**Comment by jaimemaretoli** [comment]
@cynthiapereira pode encerrar. Conforme nossa Wiki: https://wiki.mozilla.org/Brasil/Onboarding/
