### ISSUE TITLE
Iniciar processo de migração total para o Discourse

### ISSUE THREAD

**Issue by SamuelMoraesF** [mozillabrasil/metas#9]
## Meta:

O Discourse será definido como canal de discussões padrão, para tal, precisaremos desabilitar nossas listas de discussões atuais.
## Roles:
- (R)esponsável: @samuelmoraesf @cynthiapereira 
- (A)ccountable (responsable em última instância): @mozillabrasil/infra 
- (S)uporte: @FabioBeneditto @lennoazevedo @barrostecnologia
- (C)onsultado: @mozillabrasil/infra
- (I)nformado: @mozillabrasil
## Tarefas:
- [x] Notificar a migração total e a deadline de 3 meses
- [x] Criar novas sub-categorias na categoria Mozilla Brasil para os times funcionais
- [x] Atualizar as páginas e canais da comunidade para indicar o novo endereço
- [x] Criar guias sobre como utilizar o Discourse
- [x] Desativar lista

**Comment by barrosgg** [comment]
@SamuelMoraesF , vou começar a criar um texto para esclarecer as decisões da migração para o Discourse, em conjunto vou fazendo um guia para o Discourse, assim a galera pode ir se familiarizando.

**Comment by barrosgg** [comment]
Pronto, comunidade notificada a partir de hoje na lista de emails da Mozilla Brasil e Discourse da Mozilla Brasil, conforme tempo limite de 3 meses, a contar de hoje fica fixada: "**Data de desativação da lista de email: 31/AGOSTO/2016**".

**Comment by SamuelMoraesF** [comment]
Além da lista principal nossa comunidade possui outras listas inativas:
- [webapps-pt-br](https://lists.mozilla.org/listinfo/webapps-pt-br)
- [webmaker-brasil](https://lists.mozilla.org/listinfo/webmaker-brasil)
- [dev-extensions-br](https://lists.mozilla.org/listinfo/dev-extensions-br)
- [dev-l10n-pt-br](https://lists.mozilla.org/listinfo/dev-l10n-pt-br)
- [sumo-pt-br](https://groups.google.com/forum/#!forum/sumo-pt-br)

Precisamos enviar a mesma notificação para estas listas.

Vou abrir bug notificando a deadline para encerrar a lista e já vou questionar se tudo continuará arquivado no Google Groups.

**Comment by barrosgg** [comment]
@SamuelMoraesF, você possui cadastro em todas essas listas?

**Comment by SamuelMoraesF** [comment]
AFAIK, sim.

Abrirei thread nestas listas

**Comment by barrosgg** [comment]
@SamuelMoraesF, obrigado.

**Comment by barrosgg** [comment]
@SamuelMoraesF, estou colocando na lista de tarefas a criação de novas sub-categorias para os times funcionais e/ou motivos específicos, isso pode facilitar a migração da comunicação feita pelos times funcionais, dessa forma os mesmos devem solicitar aqui a criação de novas sub-categorias.
**Vou registrar aqui também a necessidade de 2 novas categorias no momento:**

---

**Sub-Categoria:** Mozilla Clubs
**Descrição:** Junte-se a comunidade de Capitães de Clubs que ensinam a web no Brasil para trocar experiências, novidades e impulsionar a rede de clubes no país.
**Cor:** "#337AB7"

**Sub-Categoria:** Mozilla Advocacy Catalyst Program
**Descrição:** Mozilla Advocacy Catalyst Program faz parte da rede Mozilla Advocacy que reúne pessoas de todo mundo para educar sobre privacidade, inclusão e alfabetização web.
**Cor:** "#6c59b4"

---

_Apenas você pode solicitar a adição de novas sub-categorias para o DevOps, correto?_

**Comment by barrosgg** [comment]
[Repositório de criação do treinamento/guia para usar o Discourse](https://github.com/mozillabrasil/treinamento-discourse), está aberto a contribuição de todos.

**Comment by barrosgg** [comment]
@lennoazevedo e @FabioBeneditto, vocês podem me ajudar na contrução do tutorial para usar o Discourse? Eu já tirei screenshot de todas as telas, agora é só escrever, está em HTML, abram o repositório.

Repositório: https://github.com/mozillabrasil/treinamento-discourse

Há outra tarefa que não foi iniciada ainda, o processo de atualização das paginas da comunidade, preciso iniciar logo.

**Comment by FabioBeneditto** [comment]
Posso sim, @barrostecnologia 

Faço fork do repositório hoje à noite e começo.

**Comment by barrosgg** [comment]
@FabioBeneditto, vlw, se quiser pode fazer direto no repositório, não precisa fazer o fork. Ah, combine com o @lennoazevedo, ele disse que vai começar a fazer, então vocês podem combinar de cada um fazer uma parte por exemplo.

**Comment by barrosgg** [comment]
Galera, acabei de criar 9 issues[1] e 1 pull request[2] com todas as atualizações necessárias no site oficial da Mozilla Brasil, @SamuelMoraesF já subiu as alterações para o server do site, já temos todos os canais atualizados e atualizações no ar!
[1] https://github.com/mozillabrasil/mozillabrasil.org.br/issues
[2] https://github.com/mozillabrasil/mozillabrasil.org.br/pulls

**Comment by barrosgg** [comment]
Bug 1279345[1] - New subcategories into Mozilla Brazil 
https://bugzilla.mozilla.org/show_bug.cgi?id=1279345

**Comment by lennoazevedo** [comment]
Trabalhando no tutorial do Discourse.
Vocês podem acompanhar e contribuir na página da wiki: https://wiki.mozilla.org/Brasil/Infra/Discourse

**Comment by barrosgg** [comment]
@lennoazevedo, obrigado, acredito que o tutorial está simples e completo, acredito que depois podemos melhorar a parte do painel de configurações, mas apenas se for necessário nós vamos melhorando com o tempo após o feedback dos voluntários. 

Estou colocando link do tutorial[3] na pagina de Infra[1] e Inicial[2] da Mozilla Brasil na wiki.
[1]https://wiki.mozilla.org/Brasil/Infra
[2] https://wiki.mozilla.org/Brasil
[3] https://wiki.mozilla.org/Brasil/Infra/Discourse

**Comment by barrosgg** [comment]
@soapdog, a sub-categoria 'Mozilla Clubs' na categoria 'Mozilla Brasil' foi criada como decidido durante a reunião no encontro da comunidade.

**Comment by barrosgg** [comment]
@nukeador @deimidis, conforme o compromisso feito pelo do nosso time, nós já concluimos todas as tarefas para o mês de junho, a única excessão no momento é a desativação da lista de email que será feita apenas em **31/AGOSTO/2016**.

**Comment by soapdog** [comment]
Acho que deveríamos manter a lista rodando por mais tempo. Um mês é pouco tempo para a migração, muita gente que assina a lista não checa os emails sempre. Seria bacana essa migração acontecer ao longo de alguns meses. Existe muito material ainda que aponta para a nossa lista, de links em wikis até apresentações passadas que estão disponíveis online.

Desativar uma lista é coisa muito séria, a Mozilla ainda tem newsgroups ativos (para aqueles que tem mais de 30 anos e ainda lembram o que é). Esse tipo de coisa não deve ser feita as pressas assim não. Vamos mudando nossa comunicação principal para o discourse, quanto o discourse for de fato o canal principal então desativamos a lista. Acabar com a lista antes do Discourse ganhar tração é tiro no pé.

**Comment by nukeador** [comment]
As I commented during the meetup my recommendations would be to avoid having both channels open for a long time. People only start using he new tools once this is the only one.

Apart from that, asking people with 1 month with instructions on how to follow discourse by email seems like a reasonable amount of time for me, but it's up to you.

**Comment by barrosgg** [comment]
@nukeador, perfeito! Nós estamos oferecendo **3 meses** para migração e **suporte a toda comunidade** que precisa usar, o tutorial para utilização do Discourse[1] já está pronto, site[2] e Wiki[3] foram atualizadas.

A lista de emails da comunidade não é frequentemente usada, acredito que os membros atuais não sentirão falta. :D

Até o momento não recebemos notificações na lista de email da comunidade relatando dificuldades e/ou pedido de suporte para uso do Discourse, acredito que é uma migração tranquila, sem problemas até o momento.

[1] https://wiki.mozilla.org/Brasil/Infra/Discourse
[2] http://mozillabrasil.org.br/
[3] https://wiki.mozilla.org/Brasil

**Comment by soapdog** [comment]
Então OK, eu gostaria de mais tempo mas se vocês acham que o tempo alocado é bom, vamos nessa.

@barrosgeraldo que tal a seguinte idéia: enviar um email a cada 15 dias para a lista avisando da migração e do tempo restante? Acha válido? Ou tipo 1 email agora em Junho, outro email em Julho e um por semana em Agosto. Para avisar bem o que está acontecendo.

Outra coisa é um CTA para o Discourse para a galera se apresentar lá, assim poderemos ter uma idéia de quem migrou...

**Comment by halcance** [comment]
Olá, acredito que a migração foi concluída com êxito já que a lista já está parada a um bom tempo.

**Comment by cpswsg** [comment]
@alipseight A "migração" que na verdade será uma desativação será implementada de fato no dia 31/08/2016.

**Comment by halcance** [comment]
Obrigado @cynthiapereira bem, então falta 2 dias para a "Migração" ser concluída.

**Comment by barrosgg** [comment]
@samuelmoraesf me confirme se a lista será desativada.

**Comment by SamuelMoraesF** [comment]
@barrosgeraldo correto, o bug já foi aberto e pedi para desativar o mais breve possível depois das 0h do dia 1º e manter o arquivo no Google Groups.

**Comment by deimidis** [comment]
Habría que enviar un último recordatorios a la lista

**Comment by jppcel** [comment]
@SamuelMoraesF  e @cynthiapereira Fiz um teste hoje, e a lista de emails ainda está aceitando novas postagens.

**Comment by halcance** [comment]
Bem, a lista foi desativada pelos membros, mas a mesma foi desativada no servidor?

**Comment by jppcel** [comment]
@alipseight A lista deveria ter sido desativada no servidor, porém, ainda não foi feito. Nós paramos de usar a lista de fato, mas a mesma não deveria estar aceitando novas postagens. :/

**Comment by cpswsg** [comment]
A migração foi concluída com sucesso!
